config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tasks do
    member do
      put :change_state
    end
  end

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'test' => 'pages#test'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord


  validates :content, presence: true, length: {minimum: 4, maximum: 300}

  belongs_to :user

  auto_html_for :content do
    html_escape
    image
    youtube(width: '100%', height: 250)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to tasks_path
    end
  end

  def about
  end

  def test
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_task, only:[:edit, :update, :show, :destroy, :change_state]

  def index

    @to_do = current_user.tasks.where(state: 'to_do')
    @doing = current_user.tasks.where(state: 'doing')
    @done = current_user.tasks.where(state: 'done')

  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(tasks_params)
    if @task.save
      flash[:notice] = "Task was created"
      redirect_to task_path(@task)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(tasks_params)
      flash[:notice] = "Task was updated"
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = "Task deleted"
    redirect_to tasks_path
  end

  def change_state
    @task.update_attributes(state: params[:state])
    flash[:notice] = "Task status changed"
    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:content, :state)
  end

  def set_task
    @task = Task.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="fa fa-circle-o-notch"></i> Taskr'.html_safe, root_path, class: 'navbar-brand'  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'My Account', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'About', about_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <% flash.each do |name,msg|   %>
      <%=  msg %>
    <% end  %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
ABOUT

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-circle-o-notch" aria-hidden="true"></i> Welcome to Taskr</h1>
  <p>Please register to continue</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/pages/test.html.erb
<div class="row">
  <div class="col-md-4">
    <h2>To Do</h2>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">To Do</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
      <div class="panel-footer">Panel footer</div>
    </div>
  </div>
  <div class="col-md-4">
    <h2>Doing</h2>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Doing</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
      <div class="panel-footer">Panel footer</div>
    </div>
  </div>
  <div class="col-md-4">
    <h2>Done</h2>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Done</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
      <div class="panel-footer">Panel footer</div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <ul>
  <% @task.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<br>
<% end %>

<%= simple_form_for @task, html: {class: 'form-signin'} do |f| %>
<%= f.input :content, required: true, autofocus: true %>
<%= f.input :state, required: true %>
<%= f.button :submit, "Save task", class: 'btn btn-primary btn-block' %>
<% end %>

<p>
  <%= link_to 'Task Listing', tasks_path %>
</p>

app/views/tasks/_task.html.erb
<!--
<tr>
  <td><%= task.content %></td>
  <td><%= task.state %></td>
  <td><%= link_to 'Show', task_path(task) %></td>
  <td><%= link_to 'Edit', edit_task_path(task) %></td>
  <td><%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: "delete?!?"} %></td>
  <td><%= link_to 'Mark as To Do', change_state_task_path(task, state: "to_do"), method: :put %></td>
  <td><%= link_to 'Mark as Doing', change_state_task_path(task, state: "doing"), method: :put %></td>
  <td><%= link_to 'Mark as Done', change_state_task_path(task, state: "done"), method: :put %></td>
</tr>
-->

<div class="panel panel-info">
  <div class="panel-heading">
    <%= link_to edit_task_path(task) do %>
      Created: <%= time_ago_in_words(task.created_at) %> ago
    <% end %>
    <%= link_to 'X', task_path(task), method: :delete, data: {confirm: "delete?!?"}, class: 'pull-right'  %>
  </div>
  <div class="panel-body"><%= raw(task.content_html) %></div>
  <div class="panel-footer">
    Mark as: <br>
    <%= link_to '<i class="fa fa-arrow-circle-left" aria-hidden="true"></i> To Do'.html_safe, change_state_task_path(task, state: "to_do"), method: :put %> |
    <%= link_to 'Doing'.html_safe, change_state_task_path(task, state: "doing"), method: :put %> |
    <%= link_to 'Done <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>'.html_safe, change_state_task_path(task, state: "done"), method: :put %>
</div>
</div>

app/views/tasks/edit.html.erb
<h2 class="text-center">Edit task</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<p>
  <%= link_to 'New Task', new_task_path %>
</p>

<div class="row">
  <div class="col-md-4">
    <h2>To Do</h2>
      <%= render @to_do %>
  </div>
  <div class="col-md-4">
    <h2>Doing</h2>
      <%= render @doing %>
  </div>
  <div class="col-md-4">
    <h2>Done</h2>
      <%= render @done %>
  </div>
</div>

app/views/tasks/new.html.erb
<h2 class="text-center">New task</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Showing task</h1>
content:
<br>
<%= @task.content %> <br>
<%= @task.state %>
<br>
<p>
  <%= link_to 'Edit', edit_task_path(@task) %>
  |
  <%= link_to 'Task Listing', tasks_path %>
</p>